export const DEFAULT_CHANNEL_AGENT_FIRST_MESSAGE =
  "Hello! How can I help you today?";

export const FACEBOOK_MESSENGER_MAX_TEXT_LENGTH = 2000;

export const CHANNEL_AGENT_SUMMARIZATION_TRIGGER_TOKENS = 6000;

export const CHANNEL_AGENT_SUMMARIZATION_KEEP_MESSAGES = 20;
